"""Demo-first entry pages sourced from the resolved feature manifest."""
from __future__ import annotations

import html
import json
from pathlib import Path

from showcase_contract.site import ContractError

TEXT = {
    "zh-CN": {
        "TITLE": "直接体验仓颉文档", "HEADLINE": "从一个 API，读懂你的库。",
        "LEAD": "用同一个 PocketKit 示例库，实际体验成员直达、重载对照、类型导航、指南与可追溯的验证结果。这里的 API 页面全部由 cjdoc 生成。",
        "OPEN": "打开完整演示", "QUICK": "快速开始", "BOUNDARY": "demo-v1 / demo-v2 是教学快照，不是 cjdoc 或标准库的正式发布版本。",
        "SAMPLE": "此代码来自示例库的源 @example。打开演示查看实际构建产生的结果。", "SOURCE_LABEL": "查看该 revision 的源码",
        "QUICK_TEXT": "下载带许可证、两个版本和固定依赖索引的示例源码。安装仓颉 SDK 与当前 revision 的 cjdoc 后，用相同 CLI 生成核心页面。",
        "READ_GUIDE": "阅读示例指南", "DOWNLOADS": "源码、配置与离线目录", "FEATURES": "按任务探索，而不是逐层找页面。",
        "FEATURE_NOTE": "实现状态与演示状态分别列出。每个入口绑定最终原生产物与浏览器场景；未完成能力保留可见说明。",
        "MACHINE": "同一份文档，也为工具准备。", "MACHINE_TEXT": "HTML、JSON、Markdown、索引与报告共享原生身份。原始报告可下载，展示层不重新计算覆盖率或兼容性。",
        "INTEGRATORS": "cjdoc 自身 API 与贡献者资料", "INTEGRATOR_TEXT": "集成生成器、查看高级参数或参与开发，从这里进入。原有 api、demo、artifacts 入口继续保留。",
        "PROVENANCE": "发布前检查最终目录、根路径、项目子路径与真实解压后的 file://。构建 revision、SDK 和输入指纹见下方；远端测试结果以对应提交的 Actions 为准。"
    },
    "en": {
        "TITLE": "Try Cangjie documentation", "HEADLINE": "Understand your library, one API at a time.",
        "LEAD": "Explore member deep links, overloads, type navigation, guides and traceable validation with the same PocketKit example library. Every API page is generated by cjdoc.",
        "OPEN": "Open the full demo", "QUICK": "Quick start", "BOUNDARY": "demo-v1 / demo-v2 are teaching snapshots, not releases of cjdoc or the standard library.",
        "SAMPLE": "This code comes from a source @example. Open the demo to inspect the actual build result.", "SOURCE_LABEL": "View source at this revision",
        "QUICK_TEXT": "Download the licensed example, both snapshots and the fixed dependency index. With the SDK and matching cjdoc revision installed, use the same CLI to reproduce the core pages.",
        "READ_GUIDE": "Read the example guide", "DOWNLOADS": "Source, configuration and offline site", "FEATURES": "Explore by task, not by directory.",
        "FEATURE_NOTE": "Implementation and demonstration states are independent. Entries resolve from final native outputs and have browser scenarios; incomplete capabilities stay visible.",
        "MACHINE": "The same documentation, ready for tools.", "MACHINE_TEXT": "HTML, JSON, Markdown, indices and reports share native identities. Raw reports are retained; presentation does not reclassify compatibility or recalculate coverage.",
        "INTEGRATORS": "cjdoc APIs and contributor resources", "INTEGRATOR_TEXT": "Integrate the generator, inspect advanced options or contribute. Existing api, demo and artifacts entries remain available.",
        "PROVENANCE": "Publication checks the final site at the root, project subpath and extracted file:// location. Revision, SDK and input fingerprints follow; consult the matching Actions run for remote evidence."
    }
}


def first(manifest: dict, feature_id: str, locale: str) -> dict:
    matches = [target for feature in manifest["features"] if feature["id"] == feature_id
               for target in feature["targets"] if target["locale"] == locale and target["resolved"]]
    if not matches:
        raise ContractError("required primary showcase target is unavailable")
    return matches[0]


def cards(manifest: dict) -> str:
    out = []
    for number, feature in enumerate(manifest["features"], 1):
        e = html.escape
        card = f'<article class="feature-card" data-feature-id="{e(feature["id"])}" data-demonstration="{e(feature["demonstration"])}">'
        card += f'<span class="feature-number">{number:02d} / {e(feature["id"])}</span><h3>{e(feature["title"])}</h3>'
        card += '<div class="feature-states"><span>Implementation / 实现: ' + e(feature["implementation"]) + '</span><span>Demo / 演示: ' + e(feature["demonstration"]) + '</span></div>'
        if feature["reason"]:
            card += '<p>' + e(feature["reason"]) + '</p>'
        if feature["targets"]:
            card += '<details><summary>操作说明 / Instructions</summary><p>' + e(feature["targets"][0]["instructions"]) + '</p></details>'
        card += '<div class="feature-targets">'
        for target in feature["targets"]:
            if target["resolved"]:
                label = target["locale"] + ' · ' + target["version"]
                card += f'<a data-target-id="{e(target["id"])}" href="{e(target["resolved"]["href"])}">{e(label)}</a>'
        out.append(card + '</div></article>')
    return '\n'.join(out)


def publish(repo: Path, site: Path, manifest: dict, metadata: dict) -> None:
    template = (repo / "site/index.html").read_text(encoding="utf-8")
    if template.count('<!-- SHOWCASE_FEATURES -->') != 1:
        raise ContractError("homepage needs exactly one feature-catalog slot")
    for locale, filename in (("zh-CN", "index.html"), ("en", "en.html")):
        values = {**TEXT[locale], "LOCALE": locale, "REPOSITORY": metadata["source"]["repository"],
                  "PRIMARY": first(manifest, "compact-members", locale)["resolved"]["href"],
                  "GUIDE": first(manifest, "guide-association", locale)["resolved"]["href"],
                  "SOURCE": metadata["source"]["repository"] + '/tree/' + manifest["revision"] + '/examples/pocketkit',
                  "BUILD": json.dumps(metadata, ensure_ascii=False, indent=2)}
        content = template
        for key, value in values.items():
            content = content.replace('__' + key + '__', html.escape(value, quote=True))
        content = content.replace('<!-- SHOWCASE_FEATURES -->', cards(manifest))
        (site / filename).write_text(content, encoding="utf-8")


def downloads(site: Path) -> None:
    (site / "downloads").mkdir(exist_ok=True)
    for locale in TEXT:
        content = f'''<!doctype html><html lang="{locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Downloads · cjdoc</title><link rel="stylesheet" href="../showcase.css"><script src="../showcase.js" defer></script></head><body data-cjdoc-doc-version="showcase"><main class="download-page"><a data-showcase-home href="../index.html">← 展示首页 / Showcase</a><h1>源码与离线目录 / Source and offline site</h1><article><h2>可复现源码 / Reproducible source</h2><p>MIT 许可，包含 demo-v1、demo-v2、support-v1 与独立诊断项目。SDK 与 cjdoc 二进制不包含在下载中。</p><p><a data-source-download href="pocketkit-source.zip" download>Download PocketKit source ZIP</a> · <a href="source-manifest.json">Source revision and SHA-256 manifest</a></p><pre><code id="download-command">python3 examples/pocketkit/reproduce.py --cjdoc /absolute/path/to/cjdoc --output ./generated --locale both</code></pre><button data-showcase-copy="download-command">Copy / 复制</button><p>从解压根目录执行。输出目录必须不存在；需要 SDK 1.1.3 和对应 revision 的 cjdoc。页面不会在浏览器内执行任意代码。</p></article><article id="offline"><h2>完整离线目录 / Complete offline site</h2><p>解压后直接打开 index.html。导航、搜索、成员展开和复制不要求联网。源码外链仍需网络。</p><p><a data-offline-download href="showcase-offline.zip" download>Download generated offline ZIP</a></p><p>离线 ZIP 不包含自身，以避免递归打包；解压后仍保留独立的源码下载。</p></article><p aria-live="polite" data-showcase-status></p></main></body></html>'''
        (site / "downloads" / (locale + ".html")).write_text(content, encoding="utf-8")
