"""Demo-first entry pages sourced from the resolved feature manifest."""
from __future__ import annotations

import html
import json
from pathlib import Path

from showcase_contract.site import ContractError
from .homepage_copy import GROUPS, LIMITS, TASKS

TEXT = {
    "zh-CN": {
        "TITLE": "直接体验仓颉文档", "HEADLINE": "从一个 API，读懂你的库。",
        "LEAD": "用同一个 PocketKit 示例库，实际体验成员直达、重载对照、类型导航、指南与可追溯的验证结果。这里的 API 页面全部由 cjdoc 生成。",
        "OPEN": "打开完整演示", "QUICK": "快速开始", "BOUNDARY": "demo-v1 / demo-v2 是教学快照，不是 cjdoc 或标准库的正式发布版本。",
        "SAMPLE": "此代码来自示例库的源 @example。打开演示查看实际构建产生的结果。", "SOURCE_LABEL": "查看该 revision 的源码",
        "QUICK_TEXT": "下载带许可证、两个版本和固定依赖索引的示例源码。完整复现流程在 Linux（含 prlimit）上运行，使用仓颉 SDK 与当前 revision 的 cjdoc。",
        "READ_GUIDE": "阅读示例指南", "DOWNLOADS": "源码、配置与离线目录", "FEATURES": "按任务探索，而不是逐层找页面。",
        "FEATURE_NOTE": "实现状态与演示状态分别列出。每个入口绑定最终原生产物与浏览器场景；未完成能力保留可见说明。",
        "MACHINE": "同一份文档，也为工具准备。", "MACHINE_TEXT": "HTML、JSON、Markdown、索引与报告共享原生身份。原始报告可下载，展示层不重新计算覆盖率或兼容性。",
        "INTEGRATORS": "cjdoc 自身 API 与贡献者资料", "INTEGRATOR_TEXT": "集成生成器、查看高级参数或参与开发，从这里进入。原有 api、demo、artifacts 入口继续保留。",
        "PROVENANCE": "发布前检查最终目录、根路径、项目子路径与真实解压后的 file://。构建 revision、SDK 和输入指纹见下方；远端测试结果以对应提交的 Actions 为准。"
    },
    "en": {
        "TITLE": "Try Cangjie documentation", "HEADLINE": "Understand your library, one API at a time.",
        "LEAD": "Explore member deep links, overloads, type navigation, guides and traceable validation with the same PocketKit example library. Every API page is generated by cjdoc.",
        "OPEN": "Open the full demo", "QUICK": "Quick start", "BOUNDARY": "demo-v1 / demo-v2 are teaching snapshots, not releases of cjdoc or the standard library.",
        "SAMPLE": "This code comes from a source @example. Open the demo to inspect the actual build result.", "SOURCE_LABEL": "View source at this revision",
        "QUICK_TEXT": "Download the licensed example, both snapshots and the fixed dependency index. The complete reproduction runs on Linux with prlimit, the SDK and cjdoc built from the matching revision.",
        "READ_GUIDE": "Read the example guide", "DOWNLOADS": "Source, configuration and offline site", "FEATURES": "Explore by task, not by directory.",
        "FEATURE_NOTE": "Implementation and demonstration states are independent. Entries resolve from final native outputs and have browser scenarios; incomplete capabilities stay visible.",
        "MACHINE": "The same documentation, ready for tools.", "MACHINE_TEXT": "HTML, JSON, Markdown, indices and reports share native identities. Raw reports are retained; presentation does not reclassify compatibility or recalculate coverage.",
        "INTEGRATORS": "cjdoc APIs and contributor resources", "INTEGRATOR_TEXT": "Integrate the generator, inspect advanced options or contribute. Existing api, demo and artifacts entries remain available.",
        "PROVENANCE": "Publication checks the final site at the root, project subpath and extracted file:// location. Revision, SDK and input fingerprints follow; consult the matching Actions run for remote evidence."
    }
}

UI_TEXT = {
    "zh-CN": {"HOME": "index.html", "SKIP": "跳到正文", "TAGLINE": "实际体验 API 文档", "NAVIGATION": "展示导航",
        "THEME": "切换明暗", "COPY": "复制", "EYEBROW": "仓颉 · 原生 API 文档", "REPRODUCE": "复现 PocketKit 示例",
        "BUILD_LABEL": "构建来源", "PLAN_LABEL": "完整演示计划", "MANIFEST": "功能清单", "NAV_LABEL": "导航索引",
        "COVERAGE_LABEL": "覆盖率", "DIFF_LABEL": "API 变化", "DOCTEST_LABEL": "示例验证", "SCHEMAS": "数据结构定义",
        "USAGE": "使用说明", "ADVANCED": "高级用法", "RELEASE": "发布流程", "LEGACY": "旧版演示入口"},
    "en": {"HOME": "en.html", "SKIP": "Skip to content", "TAGLINE": "documentation in practice", "NAVIGATION": "Showcase navigation",
        "THEME": "Light / Dark", "COPY": "Copy", "EYEBROW": "CANGJIE · NATIVE API DOCUMENTATION", "REPRODUCE": "Reproduce the PocketKit example",
        "BUILD_LABEL": "Build provenance", "PLAN_LABEL": "Full demonstration plan", "MANIFEST": "Feature manifest", "NAV_LABEL": "Navigation",
        "COVERAGE_LABEL": "Coverage", "DIFF_LABEL": "API diff", "DOCTEST_LABEL": "Doctest", "SCHEMAS": "Schemas",
        "USAGE": "Usage", "ADVANCED": "Advanced usage", "RELEASE": "Release process", "LEGACY": "Legacy demo entry"},
}


def first(manifest: dict, feature_id: str, locale: str) -> dict:
    matches = [target for feature in manifest["features"] if feature["id"] == feature_id
               for target in feature["targets"] if target["locale"] == locale and target["resolved"]]
    if not matches:
        raise ContractError("required primary showcase target is unavailable")
    return matches[0]


def cards(manifest: dict, locale: str | None = None) -> str:
    locale = locale or "zh-CN"
    language = 0 if locale == "zh-CN" else 1
    out = []
    features = {feature["id"]: feature for feature in manifest["features"]}
    grouped = {identity for _, _, _, identities in GROUPS for identity in identities}
    if set(features) - grouped:
        raise ContractError("feature has no reader task group: " + ', '.join(sorted(set(features) - grouped)))
    for group, chinese, english, identities in GROUPS:
        out.append(f'<section class="feature-group" aria-labelledby="task-{group}"><h3 id="task-{group}">{chinese if language == 0 else english}</h3><div class="feature-grid">')
        for identity in identities:
            if identity in features:
                out.append(card(features[identity], locale))
        out.append('</div></section>')
    return '\n'.join(out)


def card(feature: dict, locale: str) -> str:
    language = 0 if locale == "zh-CN" else 1
    e = html.escape
    task = TASKS[feature["id"]]
    card = f'<article class="feature-card" data-feature-id="{e(feature["id"])}" data-demonstration="{e(feature["demonstration"])}">'
    title = feature["title"].split(" / ")
    card += '<h4>' + e(title[min(language, len(title) - 1)]) + '</h4><p>' + e(task[language + 2]) + '</p>'
    if feature["id"] in LIMITS:
        card += '<p class="feature-limit">' + e(LIMITS[feature["id"]][language]) + '</p>'
    card += '<div class="feature-targets">'
    targets = [target for target in feature["targets"] if target["locale"] == locale]
    for target in targets:
        if target["resolved"]:
            label = task[language]
            if len(targets) > 1:
                label += ' · ' + target["version"] + ' · ' + (target.get("signature") or target.get("match", {}).get("title", target["id"]))
            card += f'<a data-target-id="{e(target["id"])}" lang="{e(target["locale"])}" href="{e(target["resolved"]["href"])}">{e(label)}</a>'
    card += '</div><details class="feature-evidence"><summary>' + ('实现状态与证据' if language == 0 else 'Implementation and evidence') + '</summary>'
    states = {'complete': '已实现', 'partial': '部分实现', 'not-implemented': '未实现', 'available': '可体验', 'uncovered': '未覆盖'}
    implementation = states[feature['implementation']] if language == 0 else feature['implementation']
    demonstration = states[feature['demonstration']] if language == 0 else feature['demonstration']
    card += '<p>' + ('实现：' if language == 0 else 'Implementation: ') + e(implementation)
    card += ' · ' + ('演示：' if language == 0 else 'Demo: ') + e(demonstration) + '</p>'
    card += '<a href="showcase-features.json">' + ('完整功能清单与验证入口' if language == 0 else 'Full feature manifest and evidence routes') + '</a></details></article>'
    return card

def publish(repo: Path, site: Path, manifest: dict, metadata: dict) -> None:
    template = (repo / "site/index.html").read_text(encoding="utf-8")
    if template.count('<!-- SHOWCASE_FEATURES -->') != 1:
        raise ContractError("homepage needs exactly one feature-catalog slot")
    for locale, filename in (("zh-CN", "index.html"), ("en", "en.html")):
        values = {**TEXT[locale], **UI_TEXT[locale], "LOCALE": locale, "REPOSITORY": metadata["source"]["repository"],
                  "PRIMARY": first(manifest, "compact-members", locale)["resolved"]["href"],
                  "GUIDE": first(manifest, "guide-association", locale)["resolved"]["href"],
                  "SOURCE": metadata["source"]["repository"] + '/tree/' + manifest["revision"] + '/examples/pocketkit',
                  "BUILD": json.dumps(metadata, ensure_ascii=False, indent=2)}
        content = template
        for key, value in values.items():
            content = content.replace('__' + key + '__', html.escape(value, quote=True))
        content = content.replace('<!-- SHOWCASE_FEATURES -->', cards(manifest, locale))
        content = content.replace('<!-- SHOWCASE_COVERAGE -->', coverage(manifest, locale))
        content = content.replace('<!-- SHOWCASE_GET_STARTED -->', getting_started(locale, metadata["source"]["repository"]))
        (site / filename).write_text(content, encoding="utf-8")


def getting_started(locale: str, repository: str) -> str:
    zh = locale == "zh-CN"
    title = "给自己的项目生成文档" if zh else "Document your own project"
    intro = ("先安装仓颉 SDK，再从发布页选择实际提供的平台文件，改名为 cjdoc（Windows 为 cjdoc.exe）并加入 PATH。若没有适合的平台文件，按源码构建说明安装。"
             if zh else "Install the Cangjie SDK, then choose an available platform file from Releases. Rename it to cjdoc (cjdoc.exe on Windows) and add it to PATH. If no matching file is available, follow the source build instructions.")
    links = ("下载安装包", "源码构建说明", "完整使用说明") if zh else ("Download a release", "Build from source", "Full usage guide")
    command = 'cjdoc --version\ncjdoc generate --project /path/to/your-project --format html'
    note = ("项目根目录需要 cjpm.toml 与 src/。为公开 API 添加 /** ... */ 注释，再运行上面的命令。打开项目下的 target/doc/html/index.html 即可阅读；不需要启动服务器。"
            if zh else "Your project root needs cjpm.toml and src/. Add /** ... */ comments to public APIs and run the commands above. Open target/doc/html/index.html in that project; no server is required.")
    return f'<section class="quickstart own-project" id="get-started" aria-labelledby="own-project-title"><div><h2 id="own-project-title">{title}</h2><p>{intro}</p><p><a href="{html.escape(repository, quote=True)}/releases">{links[0]}</a> · <a href="api/concepts/manual/advanced-usage.html">{links[1]}</a> · <a href="api/concepts/manual/usage.html">{links[2]}</a></p></div><div><pre><code id="own-project-command">{html.escape(command)}</code></pre><button type="button" data-showcase-copy="own-project-command">{"复制" if zh else "Copy"}</button><p>{note}</p></div></section>'


def coverage(manifest: dict, locale: str) -> str:
    """Describe demonstrated samples separately from planned capabilities."""
    features = manifest["features"]
    implemented = [feature for feature in features if feature["implementation"] != "not-implemented"]
    available = [feature for feature in implemented if feature["demonstration"] == "available"]
    partial = sum(feature["implementation"] == "partial" for feature in features)
    planned = sum(feature["implementation"] == "not-implemented" for feature in features)
    if locale == "zh-CN":
        text = (f"核心已实现能力的演示覆盖：{len(available)}/{len(implemented)}；"
                f"其中 {partial} 项实现仍有明确边界，另有 {planned} 项计划能力。"
                "可体验状态须通过本次最终目录的浏览器门禁后才允许发布，不能据此理解为全部功能已完成。")
    else:
        text = (f"Demonstration coverage of implemented capabilities: {len(available)}/{len(implemented)}; "
                f"{partial} implementations remain partial, with {planned} planned capabilities. "
                "Available samples must pass the final-site browser gate before publication; "
                "this does not claim every feature is complete.")
    return '<p class="coverage-summary" data-showcase-coverage>' + html.escape(text) + '</p>'


DOWNLOAD_TEXT = {
    "zh-CN": {
        "home": "index.html", "back": "展示首页", "title": "源码与离线目录",
        "source": "可复现源码", "license": "MIT 许可，包含 demo-v1、demo-v2、support-v1、指令检查与独立诊断项目。SDK 与 cjdoc 二进制不包含在下载中。",
        "source_zip": "下载 PocketKit 源码 ZIP", "manifest": "源码 revision 与 SHA-256 清单",
        "copy": "复制", "run": "从解压根目录执行。输出目录必须不存在；完整流程需要 Linux、prlimit、SDK 1.2.0 和对应 revision 的 cjdoc。缺少进程内存限制能力时，示例验证会明确拒绝执行。页面不会在浏览器内执行代码。",
        "offline": "完整离线目录", "use": "解压后直接打开 index.html，或打开 en.html 阅读英文首页。导航、搜索、成员展开和复制不要求联网。源码外链仍需网络。",
        "offline_zip": "下载完整离线 ZIP", "recursive": "离线 ZIP 不包含自身，以避免递归打包；解压后仍保留独立的源码下载。"
    },
    "en": {
        "home": "en.html", "back": "Showcase home", "title": "Source and offline site",
        "source": "Reproducible source", "license": "MIT licensed. Includes demo-v1, demo-v2, support-v1, directive checks and the isolated diagnostics project. The SDK and cjdoc binary are not included.",
        "source_zip": "Download PocketKit source ZIP", "manifest": "Source revision and SHA-256 manifest",
        "copy": "Copy", "run": "Run from the extracted root. The output directory must not exist. The complete workflow requires Linux, prlimit, SDK 1.2.0 and cjdoc built from the matching revision. Example validation refuses execution when process memory limits are unavailable. This page does not execute code in the browser.",
        "offline": "Complete offline site", "use": "Extract the archive and open en.html, or index.html for Chinese. Navigation, search, member expansion and copy work without a network connection. External source links still require the network.",
        "offline_zip": "Download complete offline ZIP", "recursive": "The offline archive excludes itself to avoid recursive packaging. The extracted site retains its separate source download."
    }
}


def downloads(site: Path) -> None:
    (site / "downloads").mkdir(exist_ok=True)
    for locale, raw in DOWNLOAD_TEXT.items():
        words = {key: html.escape(value) for key, value in raw.items()}
        content = f'''<!doctype html><html lang="{locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{words["title"]} · cjdoc</title><link rel="stylesheet" href="../showcase.css"><script src="../showcase.js" defer></script></head><body data-cjdoc-doc-version="showcase"><main class="download-page"><nav aria-label="Language and showcase"><a data-showcase-home href="../{words["home"]}">← {words["back"]}</a><a href="zh-CN.html" lang="zh-CN">中文</a><a href="en.html" lang="en">English</a><button type="button" data-showcase-theme>Light / Dark</button></nav><h1>{words["title"]}</h1><article><h2>{words["source"]}</h2><p>{words["license"]}</p><p><a data-source-download href="pocketkit-source.zip" download>{words["source_zip"]}</a> · <a href="source-manifest.json">{words["manifest"]}</a></p><pre><code id="download-command">python3 examples/pocketkit/reproduce.py --cjdoc /absolute/path/to/cjdoc --output ./generated --locale both</code></pre><button data-showcase-copy="download-command">{words["copy"]}</button><p>{words["run"]}</p></article><article id="offline"><h2>{words["offline"]}</h2><p>{words["use"]}</p><p><a data-offline-download href="showcase-offline.zip" download>{words["offline_zip"]}</a></p><p>{words["recursive"]}</p></article><p aria-live="polite" data-showcase-status></p></main></body></html>'''
        content = content.replace('<script src="../showcase.js"', '<script src="../theme-bootstrap.js"></script><script src="../showcase.js"')
        if locale == "zh-CN":
            content = content.replace('Light / Dark', '切换明暗').replace('aria-label="Language and showcase"', 'aria-label="语言与展示导航"')
        (site / "downloads" / (locale + ".html")).write_text(content, encoding="utf-8")
