package binary_punctuation

/** Many enum separators are not binary expressions. */
public enum ManyCases {
    | Case0
    | Case1
    | Case2
    | Case3
    | Case4
    | Case5
    | Case6
    | Case7
    | Case8
    | Case9
    | Case10
    | Case11
    | Case12
    | Case13
    | Case14
    | Case15
    | Case16
    | Case17
    | Case18
    | Case19
    | Case20
    | Case21
    | Case22
    | Case23
    | Case24
    | Case25
    | Case26
    | Case27
    | Case28
    | Case29
    | Case30
    | Case31
    | Case32
    | Case33
    | Case34
    | Case35
    | Case36
    | Case37
    | Case38
    | Case39
    | Case40
    | Case41
    | Case42
    | Case43
    | Case44
    | Case45
    | Case46
    | Case47
    | Case48
    | Case49
    | Case50
    | Case51
    | Case52
    | Case53
    | Case54
    | Case55
    | Case56
    | Case57
    | Case58
    | Case59
    | Case60
    | Case61
    | Case62
    | Case63
    | Case64
    | Case65
    | Case66
    | Case67
    | Case68
    | Case69
}

/** Nested generic punctuation is not a binary expression. */
public type Nested = Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Array<Int64>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
